// <auto-generated />
namespace Minerva.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _000_initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_000_initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201406211904373_000_initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
