// <auto-generated />
namespace Minerva.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _00_init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_00_init));
        
        string IMigrationMetadata.Id
        {
            get { return "201406170158431_00_init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
