//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minerva.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minerva.Resources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add directory.
        /// </summary>
        public static string AddDirectory {
            get {
                return ResourceManager.GetString("AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add directory to current.
        /// </summary>
        public static string AddDirectoryTitle {
            get {
                return ResourceManager.GetString("AddDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to see add actions.
        /// </summary>
        public static string AddDropDownTitle {
            get {
                return ResourceManager.GetString("AddDropDownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file.
        /// </summary>
        public static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file to current directory.
        /// </summary>
        public static string AddFileTitle {
            get {
                return ResourceManager.GetString("AddFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        public static string AssociationForm {
            get {
                return ResourceManager.GetString("AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Local Login.
        /// </summary>
        public static string CreateLocalLogin {
            get {
                return ResourceManager.GetString("CreateLocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected items.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}!.
        /// </summary>
        public static string HelloUser {
            get {
                return ResourceManager.GetString("HelloUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have a local account..
        /// </summary>
        public static string IfDontHaveLocalAccount {
            get {
                return ResourceManager.GetString("IfDontHaveLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string LocalAccountLogin {
            get {
                return ResourceManager.GetString("LocalAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account.
        /// </summary>
        public static string LogInUsingAnotherAccount {
            get {
                return ResourceManager.GetString("LogInUsingAnotherAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOff.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        public static string RegistredLogins {
            get {
                return ResourceManager.GetString("RegistredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this {0} login from your account.
        /// </summary>
        public static string RemoveLoginProvider {
            get {
                return ResourceManager.GetString("RemoveLoginProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string Shared {
            get {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared by you.
        /// </summary>
        public static string SharedByYou {
            get {
                return ResourceManager.GetString("SharedByYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared for you.
        /// </summary>
        public static string SharedForYou {
            get {
                return ResourceManager.GetString("SharedForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share selected items.
        /// </summary>
        public static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string UseAnotherServiceToLogIn {
            get {
                return ResourceManager.GetString("UseAnotherServiceToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data.
        /// </summary>
        public static string UserData {
            get {
                return ResourceManager.GetString("UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouAreAt.
        /// </summary>
        public static string YouAreAt {
            get {
                return ResourceManager.GetString("YouAreAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re logged in as &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string YouAreLoggedAs {
            get {
                return ResourceManager.GetString("YouAreLoggedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your storage.
        /// </summary>
        public static string YourStorage {
            get {
                return ResourceManager.GetString("YourStorage", resourceCulture);
            }
        }
    }
}
